### ISSUE TITLE
undefined reference to `hts_drand48()'

### ISSUE THREAD

**Issue by kcgthb** [ANGSD/angsd#115]
Hi, 

I'm trying to compile 0.919 with a global installation of htslib 1.6, and `make` fails with:
```
$ make 
HTSSRC not defined, assuming systemwide installation -lhts
echo '#define ANGSD_VERSION "0.917"' > version.h
cc -c  -O3 -D__WITH_POOL__  fet.c
[...]
g++ -c  -O3 -D__WITH_POOL__  parseArgs_bambi.cpp
g++ -MM -O3 -D__WITH_POOL__  parseArgs_bambi.cpp >parseArgs_bambi.d
g++ -O3 -D__WITH_POOL__  -o angsd *.o -lz -lpthread -lhts  -lbz2 -llzma
bam_likes.o: In function `ks_shuffle_uint16_t(unsigned long, unsigned short*)':
bam_likes.cpp:(.text+0xd41): undefined reference to `hts_drand48()'
collect2: error: ld returned 1 exit status
make: *** [angsd] Error 1
```

Any idea why this is happening?

Thanks!

**Comment by ANGSD** [comment]
Yes htslib changes some of the internals, Please pull the newest version of
angsd from GitHub. That should resolve it.

Sorry for the inconvenience.

**Comment by kcgthb** [comment]
Thanks. I just pulled `master` and see another issue now:

```
g++ -O3 ngsPSMC.cpp -o ngsPSMC psmcreader.o header.o fpsmc.o main_psmc.o hmm_psmc.o ../bfgs.o -lhts -lz
g++ -O3 scounts.cpp -lz -o scounts
gcc     msHOT2glf.c   -o msHOT2glf
msHOT2glf.c: In function ‘getFILE’:
msHOT2glf.c:38:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(size_t i=0;i<strlen(mode);i++)
   ^
msHOT2glf.c:38:3: note: use option -std=c99 or -std=gnu99 to compile your code
msHOT2glf.c: In function ‘getGz’:
msHOT2glf.c:66:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(size_t i=0;i<strlen(mode);i++)
   ^
msHOT2glf.c: In function ‘calclike’:
msHOT2glf.c:245:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0;0&&i<10;i++)
   ^
msHOT2glf.c:262:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int o=1;o<4;o++)//heterozygotic hit{
   ^
msHOT2glf.c:265:11: error: redefinition of ‘o’
   for(int o=4;o<10;o++)//non hit
           ^
msHOT2glf.c:262:11: note: previous definition of ‘o’ was here
   for(int o=1;o<4;o++)//heterozygotic hit{
           ^
msHOT2glf.c:265:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int o=4;o<10;o++)//non hit
   ^
msHOT2glf.c: In function ‘print_ind_site’:
msHOT2glf.c:300:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i=1;i<10;i++)
     ^
msHOT2glf.c:304:13: error: redefinition of ‘i’
     for(int i=0;i<10;i++)
             ^
msHOT2glf.c:300:13: note: previous definition of ‘i’ was here
     for(int i=1;i<10;i++)
             ^
msHOT2glf.c:304:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i=0;i<10;i++)
     ^
msHOT2glf.c:320:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i=0;i<4;i++){
     ^
msHOT2glf.c:324:13: error: redefinition of ‘i’
     for(int i=0;(noTrans==0&&i<2);i++)
             ^
msHOT2glf.c:320:13: note: previous definition of ‘i’ was here
     for(int i=0;i<4;i++){
             ^
msHOT2glf.c:324:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i=0;(noTrans==0&&i<2);i++)
     ^
msHOT2glf.c: In function ‘test’:
msHOT2glf.c:342:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0;i<regLen;i++) {
   ^
msHOT2glf.c:358:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i=0;i<regLen;i+=block) {
     ^
msHOT2glf.c:360:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for(int b=0;b<block;b++)
       ^
msHOT2glf.c: In function ‘main’:
msHOT2glf.c:432:11: error: redeclaration of ‘i’ with no linkage
   for(int i=0;i<argc;i++)
           ^
msHOT2glf.c:394:18: note: previous declaration of ‘i’ was here
   int j ,nsites, i;
                  ^
msHOT2glf.c:432:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0;i<argc;i++)
   ^
msHOT2glf.c:498:11: error: redefinition of ‘i’
   for(int i=0;i<howmany;i++){
           ^
msHOT2glf.c:432:11: note: previous definition of ‘i’ was here
   for(int i=0;i<argc;i++)
           ^
msHOT2glf.c:498:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i=0;i<howmany;i++){
   ^
msHOT2glf.c:520:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int n=0;n<segsites;n++){
     ^
msHOT2glf.c: In function ‘print_ind_site’:
msHOT2glf.c:326:15: warning: ignoring return value of ‘bgzf_write’, declared with attribute warn_unused_result [-Wunused-result]
     bgzf_write(outfileSAF,&homo,sizeof(double));
               ^
msHOT2glf.c:327:15: warning: ignoring return value of ‘bgzf_write’, declared with attribute warn_unused_result [-Wunused-result]
     bgzf_write(outfileSAF,&het,sizeof(double));
               ^
msHOT2glf.c: In function ‘test’:
msHOT2glf.c:349:17: warning: ignoring return value of ‘bgzf_write’, declared with attribute warn_unused_result [-Wunused-result]
       bgzf_write(outfileSAFPOS,&i,sizeof(int));
                 ^
msHOT2glf.c: In function ‘main’:
msHOT2glf.c:448:15: warning: ignoring return value of ‘bgzf_write’, declared with attribute warn_unused_result [-Wunused-result]
     bgzf_write(outfileSAF,buf,8);
               ^
msHOT2glf.c:449:15: warning: ignoring return value of ‘bgzf_write’, declared with attribute warn_unused_result [-Wunused-result]
     bgzf_write(outfileSAFPOS,buf,8);
               ^
make[1]: *** [msHOT2glf] Error 1
make[1]: Leaving directory `/dev/shm/angsd/misc'
make: *** [misc] Error 2
```

That is with GCC 4.8.5. I tried other versions with no more success. Using `-std=c99` makes the compilation stop on
```
msHOT2glf.c:195:8: error: ‘M_PI’ undeclared (first use in this function)
```

**Comment by ANGSD** [comment]
Hello the msHOT2glf was just added last week. And it looked like there was a circular dependency in the makefile. Could you please try to pull the latest version, and run a 'make clean'. If it keeps complaining, then you can remove the msHOT2glf in the All list of the misc/Makefile and it won't try to compile it. It is mostly a developer tool that I use myself.

Sorry for the inconvenience.

**Comment by kcgthb** [comment]
I just pulled the latest from git, but the exact  same issue persists.

I went back to 0.918 and it seems to work, so I'm good for now.

**Comment by ANGSD** [comment]
Ok super. It would seem that there was another typo in the misc/Makefile if you had a systemwide installation of htslib. That should be fixed now. Sorry about this. Ill close this issue. Feel free to reopen if needed.
