### ISSUE TITLE
Installation error: unsupported tapi file

### ISSUE THREAD

**Issue by msozzoni** [ANGSD/angsd#483]
Hi,
I'm trying to install ANGSD following the instruction for mac:
make CRYPTOLIB="../htslib/ 
but i get this error:

````
HTSSRC not defined; using htslib submodule
Use `make HTSSRC=/path/to/htslib` to build angsd using a local htslib installation
Use `make HTSSRC=systemwide` to build angsd using the systemwide htslib installation
git submodule update --init --recursive
make -C /Users/msozzoni/Documents/Terminale/bin/angsd/htslib
make[1]: Entering directory '/Users/msozzoni/Documents/Terminale/bin/angsd/htslib'
make[1]: Leaving directory '/Users/msozzoni/Documents/Terminale/bin/angsd/htslib'
x86_64-apple-darwin13.4.0-clang++ -O3 -o angsd *.o /Users/msozzoni/Documents/Terminale/bin/angsd/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl /Users/msozzoni/Documents/Terminale/bin/htslib/
ld: can't map file, errno=22 file '/Users/msozzoni/Documents/Terminale/bin/htslib/' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:114: angsd] Error 1

````

Then I tried to see the invocation error and I got this:

````
clang version 12.0.0
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/msozzoni/miniconda3/bin
 "/Users/msozzoni/miniconda3/bin/x86_64-apple-darwin13.4.0-ld" -demangle -lto_library /Users/msozzoni/miniconda3/lib/libLTO.12.dylib -dynamic -arch x86_64 -macosx_version_min 12.0.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o angsd abc.o abcAncError.o abcAncestry.o abcAsso.o abcCallGenotypes.o abcCounts.o abcCovar.o abcDstat.o abcDstat2.o abcError.o abcFilter.o abcFilterSNP.o abcFreq.o abcGL.o abcGetFasta.o abcHWE.o abcHWE_F.o abcHaploCall.o abcHetPlas.o abcIBS.o abcMajorMinor.o abcMcall.o abcMismatch.o abcPSMC.o abcRAD.o abcSaf.o abcScounts.o abcSmartCounts.o abcSnpTools.o abcTemplate.o abcTemplate2.o abcWriteBcf.o abcWriteFasta.o abcWritePlink.o abcWriteVcf.o aio.o analysisFunction.o ancestral_likes.o angsd.o argStruct.o bam_likes.o bammer_main.o beagleReader.o bfgs.o bgenReader.o chisquare.o cigstat.o fet.o filterStrandBias.o from_samtools.o gatk_likes.o glfReader.o glfReader_text.o kprobaln.o mUpPile.o makeReadPool.o malloc_wrap.o mpileup.o multiReader.o parseArgs_bambi.o phys_genolike_calc.o phys_likes.o pooled_alloc.o pop1_read.o prep_sites.o printRes.o sample.o shared.o simple_likes.o soap_likes.o vcfReader.o /Users/msozzoni/Documents/Terminale/bin/angsd/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl /Users/msozzoni/Documents/Terminale/bin/htslib/ -lc++ -lSystem /Users/msozzoni/miniconda3/lib/clang/12.0.0/lib/darwin/libclang_rt.osx.a
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libz.tbd' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

````
is there any way to resolve this issue?

Thank you in advance

Marcella

**Comment by isinaltinkaya** [comment]
Hi,

Can you try using the following command?

```
make CRYPTOLIB=""
```

This should fix it, but please feel free to reopen the issue if you experience more issues.

**Comment by msozzoni** [comment]
Hi, 

I've tried to use 
'''
make CRYPTOLIB=""
'''
but I got the same error 

'''
HTSSRC not defined; using htslib submodule
Use `make HTSSRC=/path/to/htslib` to build angsd using a local htslib installation
Use `make HTSSRC=systemwide` to build angsd using the systemwide htslib installation
git submodule update --init --recursive
make -C /Users/msozzoni/Documents/Terminale/bin/angsd/htslib
make[1]: Entering directory '/Users/msozzoni/Documents/Terminale/bin/angsd/htslib'
make[1]: Leaving directory '/Users/msozzoni/Documents/Terminale/bin/angsd/htslib'
x86_64-apple-darwin13.4.0-clang++ -O3 -o angsd *.o /Users/msozzoni/Documents/Terminale/bin/angsd/htslib/libhts.a -lz -lm -lbz2 -llzma -lpthread -lcurl /Users/msozzoni/Documents/Terminale/bin/htslib/
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libbz2.tbd' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:114: angsd] Error 1
'''

**Comment by isinaltinkaya** [comment]
Hi,

I think the issue may be related to https://developer.apple.com/forums/thread/672939.

Can you try the command below?

```
xcode-select --install
```

If it still does not work, I would recommend trying a full upgrade
```
brew upgrade llvm
brew upgrade gcc
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by msozzoni** [comment]
Hi, 

I've tried running both the command you suggested and the full upgrade, but I still get the same error.
