### ISSUE TITLE
empty output files

### ISSUE THREAD

**Issue by Sven-Winter** [ANGSD/angsd#581]
Hi, 

I am trying to use angsd to call SNP likelihoods for my samples for each chromosome in parallel to speed things up. However, the output files (e.g., snaps.beagle.gz, etc. ) are empty except for the log files and the snps.arg files. 
I have tried multiple versions of angsd and parallel but it is always the same.  I had the same situation on a different server before but we could never figure out what the issue was. I have also tried without parallel with the same result.

I use the following command as part of a sbatch job submission on our HPC cluster:

parallel -j 18 \
  "angsd -b ./bamlist -ref ../reference.fasta -r {} -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -baq 2 -minMapQ 30 -minQ 30 -minInd 41 -setMinDepth 272 -setMaxDepth 972 -skipTriallelic 1 -minMaf 0.05 -sb_pval 1e-6 -hwe_pval 1e-6 -hetbias_pval 1e-6 -SNP_pval 1e-6 -doSnpStat 1 -doHWE 1 -doCounts 1 -doMajorMinor 1 -doMaf 2 -doPost 1 -doGeno 8 -doGlf 2 -GL 1 -P 4 -out ./{}.snps &> ./{}.angsd.log" \
  ::: NC_0693{80..88}.1 NC_0693{90..98}.1

Any idea what the issue might be?

**Comment by Sven-Winter** [comment]
Has anyone had the same issue? We have encountered this multiple times on a variety of servers and clusters. I would really appreciate any help, as I am currently really stuck and cannot move forward with my project. 

I have tried different ANGSD versions, different subsets of input data, different filtering settings but nothing changed.

Thanks Sven

**Comment by isinaltinkaya** [comment]
Hi @Sven-Winter,

Could you please run the following command:

```
angsd -b ./bamlist -ref ../reference.fasta -r NC_069380.1 -doSnpStat 1 -doHWE 1 -doCounts 1 -doMajorMinor 1 -doMaf 2 -doPost 1 -doGeno 8 -doGlf 2 -GL 1 -out test1_581
```

Then

* Check if output files `test1_581.*` are empty
* Share `test1_581.arg`

Thanks!
Best wishes,
Isin

**Comment by isinaltinkaya** [comment]
Dear @Sven-Winter,

Can you check the flags in your input bam files, e.g. :

```
samtools view sample1.bam | cut -f2 | sort -u
```

What happened may be due to all reads being skipped by angsd due to their flags, e.g. having a flag >= 512.

Best wishes,
Isin

**Comment by Sven-Winter** [comment]
Dear @isinaltinkaya, 

thanks again but that seems not to be the issue. 
The only flags I get are: 
147
163
83
99

Best wishes, 
Sven

**Comment by isinaltinkaya** [comment]
Dear @Sven-Winter,

Can you try using `bcftools mpileup` with your data? This is to ensure that this is due to a bug in angsd and not the dataset.

e.g. 

```
bcftools mpileup -f ../reference.fasta -b ./bamlist -r NC_069380.1 
```

**Comment by bferrette** [comment]
Hi,

I have been experiencing the same error, a recurrent error in ANGSD that was solved in previous versions, but it looks like it is coming back.
The software starts, the log files are created, and the outputs are always empty.
How to solve this issue?

**Comment by isinaltinkaya** [comment]
Dear @bferrette,

I can look into this if you can provide a minimal reproducible example:

- the command you run
- input files to test the command (e.g. this can be a subset of your data) 
- the version number of angsd where the issue was resolved
- the version number of angsd  where the issue came back

Best,
Isin

**Comment by bferrette** [comment]
Dear isinaltinkaya,

Here is the log from ansgd:
        -> angsd version: 0.941-17-ge6967e6 (htslib: 1.17) build(Jun 25 2023 15:07:03)
        -> angsd -b ./bamlist -ref assembly.fasta -GL 1 -P 8 -out ./angsd -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -C 50 -baq 1 -minMapQ 30 -minQ 30 -minInd 86 -doSNPstat 1 -doHWE 1 -sb_pval 1e-6 -hwe_pval 1e-6 -hetbias_pval 1e-6 -doCounts 1 -setMinDepth 1 -setMaxDepth 77 -doMajorMinor 1 -skipTriallelic 1 -doMaf 2 -doPost 1 -minMaf -1 -SNP_pval 1e-6 -doGeno 8 -geno_minDepth 3 -doGlf 2
        -> Inputtype is BAM/CRAM
[multiReader] 96 samples in 96 input files
        -> Reading fasta: ../../../assembly/draft/assembly.fasta
        -> SNP-filter using a pvalue: 1.000000e-06 correspond to 23.928127 likelihood units
        -> Parsing 96 number of samples

        -> Allocated ~ 10 million nodes to the nodepool, this is not an estimate of the memory usage
        -> Printing at chr: Seq_1 pos:1440777 chunknumber 100 contains 5389 sites
        -> Printing at chr: Seq_1 pos:2213904 chunknumber 200 contains 7496 sites

        -> Allocated ~ 20 million nodes to the nodepool, this is not an estimate of the memory usage
        -> Printing at chr: Seq_2 pos:1099133 chunknumber 300 contains 282 sites
        -> Printing at chr: Seq_2 pos:3158003 chunknumber 400 contains 152 sites
        -> Printing at chr: Seq_3 pos:1739194 chunknumber 500 contains 6694 sites
        -> Printing at chr: Seq_3 pos:2408225 chunknumber 600 contains 257 sites
        -> Printing at chr: Seq_4 pos:1426535 chunknumber 700 contains 13789 sites

BFCtools works fine in the same inputs, but angsd starts, but I always have an empty output. In my last publication, I used version 0.935, but the latest stable version has this issue that we experienced before.

This is the arg file from angsd:
	-> angsd version: 0.941-17-ge6967e6 (htslib: 1.17) build(Jun 25 2023 15:07:03)
	-> angsd -b ./bamlist -ref assembly.fasta -GL 1 -P 8 -out angsd -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -C 50 -baq 1 -minMapQ 30 -minQ 30 -minInd 86 -doSNPstat 1 -doHWE 1 -sb_pval 1e-6 -hwe_pval 1e-6 -hetbias_pval 1e-6 -doCounts 1 -setMinDepth 1 -setMaxDepth 77 -doMajorMinor 1 -skipTriallelic 1 -doMaf 2 -doPost 1 -minMaf -1 -SNP_pval 1e-6 -doGeno 8 -geno_minDepth 3 -doGlf 2 
	-> Sun Jun 25 15:08:09 2023
----------------
multiReader.cpp:
	-nLines	50	(Number of lines to read)
	-beagle	(null)	(Beagle Filename (can be .gz))
	-bgen	(null)	(Bgen Filename)
	-vcf-GL	(null)	(vcf Filename (can be bcf compressed or uncompressed))
	-vcf-PL	(null)	(vcf Filename (can be bcf compressed or uncompressed))
	-vcf-GP	(null)	(vcf Filename (can be bcf compressed or uncompressed))(*not used)
	-glf	(null)	(glf Filename (can be .gz))
	-pileup	(null)	(pileup Filename (can be .gz))
	-intName 1	(Assume First column is chr_position)
	-isSim	0	(Simulated data assumes ancestral is A)
	-nInd	0		(Number of individuals)
	-minQ	30	(minimum base quality; only used in pileupreader)
	-fai	(null)	(fai file)
	-minQ	30	(minimum base quality; only used in pileupreader)
----------------
multiReader.cpp:
---------------
parseArgs_bambi.cpp: bam reader:
	-bam/-b		./bamlist	(list of BAM/CRAM files)
	-i		./bamlist	(Single BAM/CRAM file)
	-r		(null)	Supply a single region in commandline (see examples below)
	-rf		(null)	Supply multiple regions in a file (see examples below)
	-remove_bads	1	Discard 'bad' reads, (flag & 512) 
	-uniqueOnly	1	Discards reads that doesn't map uniquely
	-show		0	Mimic 'samtools mpileup' also supply -ref fasta for printing reference column
	-minMapQ	30	Discard reads with mapping quality below
	-minQ		30	Discard bases with base quality below
	-trim		0	Number of based to discard at both ends of the reads
	-trim		0	Number of based to discard at 5' ends of the reads
	-trim		0	Number of based to discard at 3' ends of the reads
	-only_proper_pairs 1	Only use reads where the mate could be mapped
	-C		50	adjust mapQ for excessive mismatches (as SAMtools), supply -ref
	-baq		1	adjust qscores around indels (1=normal baq 2= extended(as SAMtools)), supply -ref
	-redo-baq		0 (recompute baq, instead of using BQ tag)
	-setQscore	-1	Set qscore to this value, relevant for missing qscores
	-checkBamHeaders 1	Exit if difference in BAM headers
	-doCheck	1	Keep going even if datafile is not suffixed with .bam/.cram
	-downSample	0.000	Downsample to the fraction of original data
	-nReads		50	Number of reads to pop from each BAM/CRAMs
	-minChunkSize	250	Minimum size of chunk sent to analyses
	--ignore-RG	1	(dev only)
	+RG		(null)	Readgroups to include in analysis(can be filename)
	+LB		(null)	Libraries to include in analysis(can be filename)

Examples for region specification:
		chr:		Use entire chromosome: chr
		chr:start-	Use region from start to end of chr
		chr:-stop	Use region from beginning of chromosome: chr to stop
		chr:start-stop	Use region from start to stop from chromosome: chr
		chr:site	Use single site on chromosome: chr
--------------------
[shared.cpp:init()]
	-nThreads	8	Number of threads to use
	-nQueueSize	-1	Maximum number of queud elements
	-howOften	100	How often should the program show progress
--------------
abcFilter.cpp:
	-sites		(null)	(File containing sites to keep (chr pos))
	-sites		(null)	(File containing sites to keep (chr regStart regStop))
	-sites		(null)	(File containing sites to keep (chr pos major minor))
	-sites		(null)	(File containing sites to keep (chr pos major minor af ac an))
	-minInd		86	Only use site if atleast minInd of samples has data
	-setMinDepthInd	1	Only use site if atleast minInd of samples has this minimum depth 
	-capDepth	-1	Only use the first capDepth bases
	-strict	1	 (experimental)
	1) You can force major/minor by -doMajorMinor 3
	And make sure file contains 4 columns (chr tab pos tab major tab minor)
---------------
abcCounts.cpp:
	-doCounts	1	(Count the number A,C,G,T. All sites, All samples)
	-doEBD	0	(Calculate effective basedepth, this will be output in bcffile, beta)
	-minQfile	(null)	 file with individual quality score thresholds)
	-setMaxDepth	77	(If total depth is larger then site is removed from analysis.
				 -1 indicates no filtering)
	-setMinDepth	1	(If total depth is smaller then site is removed from analysis.
				 -1 indicates no filtering)
	-setMaxDepthInd	-1	(If depth persample is larger then individual is removed from analysis (from site).
				 -1 indicates no filtering)
	-setMinDepthInd	-1	(If depth persample is smaller then individual is removed from analysis (from site).
				 -1 indicates no filtering)
	-minInd		86	(Discard site if effective sample size below value.
				 0 indicates no filtering)
	-setMaxDiffObs	0	(Discard sites where we observe to many different alleles.
				 0 indicates no filtering)
Filedumping:
	-doDepth	0	(dump distribution of seqdepth)	.depthSample,.depthGlobal
	  -maxDepth	100	(bin together high depths)
	-doQsDist	0	(dump distribution of qscores)	.qs
	-minQ	30	(minimumQ)
	-dumpCounts	0
	  1: total seqdepth for site	.pos.gz
	  2: seqdepth persample		.pos.gz,.counts.gz
	  3: A,C,G,T sum over samples	.pos.gz,.counts.gz
	  4: A,C,G,T sum every sample	.pos.gz,.counts.gz
	  5: mean read length	.pos.gz,.counts.gz
	-iCounts	0 (Internal format for dumping binary single chrs,1=simple,2=advanced)
	-qfile	(null)	(Only for -iCounts 2)
	-ffile	(null)	(Only for -iCounts 2)
---------------------
abcGL.cpp:
	-GL=1: 
	1: SAMtools
	2: GATK
	3: SOAPsnp
	4: SYK
	5: phys
	6: Super simple sample an allele type GL. (1.0,0.5,0.0)
	7: outgroup gls
	-trim		0		(zero means no trimming)
	-tmpdir		angsd_tmpdir/	(used by SOAPsnp)
	-errors		(null)		(used by SYK)
	-minInd		86		(0 indicates no filtering)

Filedumping:
	-doGlf	2
	1: binary glf (10 log likes)	.glf.gz
	2: beagle likelihood file	.beagle.gz
	3: binary 3 times likelihood	.glf.gz
	4: text version (10 log likes)	.glf.gz
	5: binary saf files (usefull for realSFS)	.glf.gz

---------------------
abcGL.cpp:
	-GL=1: 
	1: SAMtools
	2: GATK
	3: SOAPsnp
	4: SYK
	5: phys
	6: Super simple sample an allele type GL. (1.0,0.5,0.0)
	7: outgroup gls
	-trim		0		(zero means no trimming)
	-tmpdir		angsd_tmpdir/	(used by SOAPsnp)
	-errors		(null)		(used by SYK)
	-minInd		86		(0 indicates no filtering)

Filedumping:
	-doGlf	2
	1: binary glf (10 log likes)	.glf.gz
	2: beagle likelihood file	.beagle.gz
	3: binary 3 times likelihood	.glf.gz
	4: text version (10 log likes)	.glf.gz
	5: binary saf files (usefull for realSFS)	.glf.gz

	-> doMcall=0
-------------------
abcMajorMinor.cpp:
	-doMajorMinor	1
	1: Infer major and minor from GL
	2: Infer major and minor from allele counts
	3: use major and minor from a file (requires -sites file.txt)
	4: Use reference allele as major (requires -ref)
	5: Use ancestral allele as major (requires -anc)
	6: Use EBD for major and minor (requires read data)
	7: Use EBD for minor (Major is ref) (requires -ref and read data, (similar to SAMtools))
	-rmTrans: remove transitions 0
	-skipTriallelic	1
------------------------
abcFreq.cpp:
-doMaf	2 (Calculate persite frequencies '.mafs.gz')
	1: Frequency (fixed major and minor)
	2: Frequency (fixed major unknown minor)
	4: Frequency from genotype probabilities
	8: AlleleCounts based method (known major minor)
	NB. Filedumping is supressed if value is negative
-doPost	1	(Calculate posterior prob 3xgprob)
	1: Using frequency as prior
	2: Using uniform prior
	3: Using SFS as prior (still in development)
	4: Using reference panel as prior (still in development), requires a site file with chr pos major minor af ac an
Filters:
	-minMaf  	-1.000000	(Remove sites with MAF below)
	-SNP_pval	0.000001	(Remove sites with a pvalue larger)
	-rmSNPs 	0	(Remove infered SNPs instead of keeping them (pval > SNP_pval)
	-rmTriallelic	0.000000	(Remove sites with a pvalue lower)
	-forceMaf	0	(Write .mafs file when running -doAsso (by default does not output .mafs file with -doAsso))
	-skipMissing	1	(Set post to 0.33 if missing (do not use freq as prior))

If you need more information, I can provide it.

All the best, and thanks for your reply.

**Comment by Sven-Winter** [comment]
Hi @isinaltinkaya, 

I just wanted to confirm that bcftools mpileup works just fine for my dataset as well. 

Thanks again for your help 

Sven

**Comment by isinaltinkaya** [comment]
Hi @Sven-Winter and @bferrette,

Thank you for the replies!

Could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) we can run to observe and investigate this issue? It can be a small subset of your data, e.g. only one small chromosome. 

Best wishes,
Isin

**Comment by ANGSD** [comment]
Yes, that would be nice. I am puzzled about this.

What happens if you do

./angsd -bam your.list -domajorminor 1 -gl 1 -domaf 1

And then just let it run for some time. This should do no filtering and do the most basic analyses and output results for all sites where there is data.

**Comment by Sven-Winter** [comment]
Hi @ANGSD @isinaltinkaya, 

Thanks for your help. I will need time to get a sample dataset small enough to send. However, using the most basic command, it works and writes the mafs file. I tried a view combination of options, and it seems that as soon as I add -doSNPstat 1 the files stay empty but there is no error.

**Comment by ANGSD** [comment]
It seems to work at my end with these commands:

$ angsd % ./angsd -b list -r 1 -domaf 1 -gl 1 -domajorminor 1 -dosnpstat 1         
	-> angsd version: 0.941-17-ge6967e6 (htslib: 1.14-9-ge769401) build(Jun 27 2023 14:55:57)
	-> ./angsd -b list -r 1 -domaf 1 -gl 1 -domajorminor 1 -dosnpstat 1 
	-> No '-out' argument given, output files will be called 'angsdput'
	-> Inputtype is BAM/CRAM
[multiReader] 33 samples in 33 input files
must use -doHWE 1, to test for HWE
$ ./angsd -b list -r 1 -domaf 1 -gl 1 -domajorminor 1 -dosnpstat 1 -dohwe 1
	-> angsd version: 0.941-17-ge6967e6 (htslib: 1.14-9-ge769401) build(Jun 27 2023 14:55:57)
	-> ./angsd -b list -r 1 -domaf 1 -gl 1 -domajorminor 1 -dosnpstat 1 -dohwe 1 
	-> No '-out' argument given, output files will be called 'angsdput'
	-> Inputtype is BAM/CRAM
[multiReader] 33 samples in 33 input files
	-> Parsing 33 number of samples 
	-> Region lookup 1/1
	-> Printing at chr: 1 pos:14086716 chunknumber 300 contains 251 sites
	-> Done reading data waiting for calculations to finish
	-> Done waiting for threads
	-> Output filenames:
		->"angsdput.arg"
		->"angsdput.mafs.gz"
		->"angsdput.hwe.gz"
		->"angsdput.snpStat.gz"
	-> Tue Jun 27 15:00:24 2023
	-> Arguments and parameters for all analysis are located in .arg file
	-> Total number of sites analyzed: 100197
	-> Number of sites retained after filtering: 100197 
	[ALL done] cpu-time used =  4.64 sec
	[ALL done] walltime used =  5.00 sec
$ ls -s angsdput.*
    24 angsdput.arg		  1936 angsdput.hwe.gz		     8 angsdput.saf.gz		     8 angsdput.saf.pos.gz
113208 angsdput.glf.gz		   904 angsdput.mafs.gz		     8 angsdput.saf.idx		  4120 angsdput.snpStat.gz

Could you try to incrementally include your other filter parameters until you figure out which one is too strict for your data?

**Comment by Sven-Winter** [comment]
Hi @ANGSD 
I ran the exact same command as you in the latest stable angsd version 0.940 (./angsd -b list -r 1 -domaf 1 -gl 1 -domajorminor 1 -dosnpstat 1 -dohwe 1), and the output files are empty. I did not even include any filters. As soon as I add '-dosnpstat 1'  the output stays empty. I have also tried it with other bam files but that does not change anything.

Is it possible that this is an issue caused by our server ?

**Comment by Sven-Winter** [comment]
Hi @ANGSD, 
here is the hwe file: 

Chromo  Position        Major   Minor   hweFreq Freq    F       LRT     p-value
NC_069398.1     1       T       A       0.000001        0.000150        0.666617        -1.548903e-02   1.000000e+00
NC_069398.1     2       T       A       0.000001        0.000150        0.666617        -1.550764e-02   1.000000e+00
NC_069398.1     3       T       A       0.000001        0.000150        0.666617        -1.550769e-02   1.000000e+00
NC_069398.1     4       A       C       0.000001        0.000150        0.666617        -1.551913e-02   1.000000e+00
NC_069398.1     5       G       A       0.000001        0.000150        0.666617        -1.562180e-02   1.000000e+00
NC_069398.1     6       G       T       0.000008        0.000150        0.666617        -1.244064e-02   1.000000e+00
NC_069398.1     7       C       A       0.000001        0.000150        0.666617        -1.545435e-02   1.000000e+00
NC_069398.1     8       T       A       0.000003        0.000150        0.666617        -1.537490e-02   1.000000e+00
NC_069398.1     9       T       A       0.000003        0.000150        0.666617        -1.537538e-02   1.000000e+00
NC_069398.1     10      G       A       0.000003        0.000150        0.666617        -1.534648e-02   1.000000e+00
NC_069398.1     11      C       A       0.000002        0.000150        0.666617        -1.547633e-02   1.000000e+00
NC_069398.1     12      T       A       0.000002        0.000150        0.666617        -1.563387e-02   1.000000e+00
NC_069398.1     13      T       A       0.000002        0.000150        0.666617        -1.567480e-02   1.000000e+00
NC_069398.1     14      A       T       0.000002        0.000150        0.666617        -1.466394e-02   1.000000e+00
NC_069398.1     15      T       A       0.000001        0.000150        0.666617        -1.571314e-02   1.000000e+00
NC_069398.1     16      T       A       0.000001        0.000150        0.666617        -1.571557e-02   1.000000e+00
NC_069398.1     17      T       A       0.000001        0.000150        0.666617        -1.575959e-02   1.000000e+00
NC_069398.1     18      T       A       0.000001        0.000150        0.666617        -1.576030e-02   1.000000e+00
NC_069398.1     19      T       A       0.000001        0.000150        0.666617        -1.576030e-02   1.000000e+00
NC_069398.1     20      T       A       0.000001        0.000150        0.666617        -1.576067e-02   1.000000e+00
NC_069398.1     21      C       A       0.000001        0.000150        0.666617        -1.614053e-02   1.000000e+00
NC_069398.1     22      A       C       0.000001        0.000150        0.666617        -1.614060e-02   1.000000e+00
NC_069398.1     23      T       A       0.000001        0.000150        0.666617        -1.615942e-02   1.000000e+00
NC_069398.1     24      A       C       0.000001        0.000150        0.666617        -1.610257e-02   1.000000e+00
NC_069398.1     25      A       C       0.000001        0.000150        0.666617        -1.615854e-02   1.000000e+00
NC_069398.1     26      C       A       0.000001        0.000150        0.666617        -1.615937e-02   1.000000e+00
NC_069398.1     27      T       A       0.000001        0.000150        0.666617        -1.615927e-02   1.000000e+00
NC_069398.1     28      G       A       0.000001        0.000150        0.666617        -1.614017e-02   1.000000e+00
NC_069398.1     29      C       A       0.000001        0.000150        0.666617        -1.615462e-02   1.000000e+00
NC_069398.1     30      T       A       0.000001        0.000150        0.666617        -1.615844e-02   1.000000e+00
NC_069398.1     31      T       A       0.000001        0.000150        0.666617        -1.615922e-02   1.000000e+00
NC_069398.1     32      T       A       0.000001        0.000150        0.666617        -1.615917e-02   1.000000e+00
NC_069398.1     33      C       A       0.000001        0.000150        0.666617        -1.614061e-02   1.000000e+00
NC_069398.1     34      T       A       0.000001        0.000150        0.666617        -1.615936e-02   1.000000e+00
NC_069398.1     35      T       A       0.000001        0.000150        0.666617        -1.615942e-02   1.000000e+00
NC_069398.1     36      G       A       0.000001        0.000150        0.666617        -1.576003e-02   1.000000e+00
NC_069398.1     37      A       C       0.000001        0.000150        0.666617        -1.614580e-02   1.000000e+00
NC_069398.1     38      G       A       0.000001        0.000150        0.666617        -1.615928e-02   1.000000e+00
NC_069398.1     39      A       T       0.000007        0.000150        0.666617        -1.309733e-02   1.000000e+00
NC_069398.1     40      T       A       0.000001        0.000150        0.666617        -1.615723e-02   1.000000e+00
NC_069398.1     41      A       C       0.000001        0.000150        0.666617        -1.614041e-02   1.000000e+00
NC_069398.1     42      T       A       0.000001        0.000150        0.666617        -1.615943e-02   1.000000e+00
NC_069398.1     43      A       C       0.000001        0.000150        0.666617        -1.615932e-02   1.000000e+00
NC_069398.1     44      A       C       0.000001        0.000150        0.666617        -1.615818e-02   1.000000e+00

**Comment by Sven-Winter** [comment]
Yes, sure! Here is the .arg file from the last test run. 
[angsdput.arg.txt](https://github.com/ANGSD/angsd/files/11906781/angsdput.arg.txt)

**Comment by Sven-Winter** [comment]
Any ideas?

**Comment by ANGSD** [comment]
Sorry for the lack of reply. Could you test with a single bam file to validate that it outputs something? If it doesn't output anything, it would be very useful if you could give us a very small subset of the bamfile.

**Comment by Sven-Winter** [comment]
No worries. Thank you again for your help. 
I have tried it with only one bam file, and still no output. 
I have split the bam file of one individual by chromosome and you can find the bam for the smallest chromosome here: 
https://www.dropbox.com/t/HsNh447QWnNgRyzP 
I hope that is small enough

**Comment by deborahmleigh** [comment]
Has this issue been resolved? I have exactly the same issue with "-doSnpStat 1" I can even add "-doSnpStat 0" and get output but as soon as I change the flag to 1, it does not seem to work consistently. Any ideas what the issue would be?

**Comment by Sven-Winter** [comment]
Hi @deborahmleigh, 
I have not found a solution yet and as you can see there was not really any update in months.

**Comment by deborahmleigh** [comment]
Yea I just removed the flag because it is obviously doing something I don't understand.

**Comment by Sven-Winter** [comment]
Hi @ANGSD, 
 we would still very much appreciate some help. 
I have spent a view hours today trying out all different options and this command works fine: 

angsd -b $4/bamlist -ref $1 -GL 1 -P 4 -out $4/cheetah \
  -remove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -baq 2 \
  -minMapQ 30 -minQ 30 -minInd ${min_ind}  \
  -doSnpStat 1 -doHWE 1 -sb_pval 1e-6 -hwe_pval 1e-6 -hetbias_pval 1e-6 \
  -doCounts 1 -setMinDepth ${min_dp} -setMaxDepth ${max_dp} \
  -doMajorMinor 1 -skipTriallelic 1 \
  -doMaf 2  -doPost 1 \
  -doGeno 8 -doGlf 2 \
  &> $4/angsd.log

However, as soon as I add any -minMaf or SNP_pval filter it apparently filters out all positions. 

Any help is greatly appreciated 

Thanks

**Comment by deborahmleigh** [comment]
HI Sven, 

I am certainly not super angsd literate but I removed all the filters one by one - it was a combination of this flag "-doSnpStat " and a specific individual. In the end I removed this flag because it obviously doing more then it says... Try changing the flag to 0 and see if it stops removing the sites. 

Cheers
D

**Comment by Sven-Winter** [comment]
@deborahmleigh 
Thanks for the quick reply. However for me, apparently, it is not the -doSnpStat option. It does not matter if I include it or not. As soon as I use -minMaf or -SNP_pval, it does not work.

**Comment by stuartwillis** [comment]
I can confirm that this is still an issue: some combinations of data (different subsets of the same data) cause this error (all sites filtered) when -doSNPstat 1 is invoked, in my case in combination with -sites (with major/minor) and -rf. And occurs for all recent versions of ANGSD (0.935, 940, and 941) and whether compiled from source or installed with conda. In my case, removing -doSNPstat 1 circumvents empty output.

MOREOVER, before I realized that -doSNPstat 1 was the culprit, I found that if I took the same data and divided the sites/region files into subsets by chromosome (using linux split on the rf file, then grep -f with each of those on the sites file), the analysis ran as expected. Bonus: doing that, I could parallelize the different subsets, making the analysis MUCH faster (almost linearly less with the degree of division). Sewing all the different output files back together in order is a pain, but worth the pain and may not be necessary depending on the application (e.g. for input to ngsLD I usually subset chromosomes anyway). I think the same could be done just with an rf file (without sites).

So, if you want doSNPstat and your analysis is still choking, try sub-dividing and parallelizing it. I can provide some additional bash code for that if desired.
